name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**' # This triggers the workflow on pull requests to any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test
